/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tetris.gui;

import tetris.lib.utils.Configurations;
import tetris.lib.utils.SoundPlayer;

/**
 *
 * @author ajose
 */
public class Configs extends javax.swing.JDialog {
    private SoundPlayer soundp;
    private Configurations config;
    private Boolean isFirstTime = true;
    

    /**
     * *
     *
     * @param parent
     * @param modal
     * @param config
     */
    public Configs(java.awt.Frame parent, boolean modal, Configurations config, SoundPlayer soundp) {
        super(parent, modal);
        this.config = config;
        this.soundp = soundp;
        this.config.ReadConfig();
        initComponents();
        switch(this.config.getDifficulty()){
            case 0 -> RB_Easy.setSelected(true);
            case 1 -> RB_Normal.setSelected(true);
            case 2 -> RB_Hard.setSelected(true);
        }
        volumeMusic.setValue((int) this.soundp.getVolumeToSlider());
        this.soundp.changeVolume(volumeMusic.getValue());
        lines.setValue(this.config.getLines());
        cols.setValue(this.config.getCols());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lines = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        volumeMusic = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        RB_Easy = new javax.swing.JRadioButton();
        RB_Normal = new javax.swing.JRadioButton();
        RB_Hard = new javax.swing.JRadioButton();
        cols = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lines.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lines.setModel(new javax.swing.SpinnerNumberModel(20, 8, null, 1));
        lines.setBorder(javax.swing.BorderFactory.createTitledBorder("Linhas"));
        lines.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lines.setFocusable(false);
        lines.setRequestFocusEnabled(false);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Repor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Música");

        volumeMusic.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                volumeMusicStateChanged(evt);
            }
        });

        jLabel2.setText("Dificuldade");

        RB_Easy.setText("Fácil");
        RB_Easy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_EasyActionPerformed(evt);
            }
        });

        RB_Normal.setText("Normal");
        RB_Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_NormalActionPerformed(evt);
            }
        });

        RB_Hard.setText("Difícil");
        RB_Hard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_HardActionPerformed(evt);
            }
        });

        cols.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cols.setModel(new javax.swing.SpinnerNumberModel(20, 8, null, 1));
        cols.setBorder(javax.swing.BorderFactory.createTitledBorder("Linhas"));
        cols.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cols.setFocusable(false);
        cols.setRequestFocusEnabled(false);

        jLabel3.setText("Dimensão");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(volumeMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RB_Easy)
                                        .addGap(30, 30, 30)
                                        .addComponent(RB_Normal)
                                        .addGap(26, 26, 26)
                                        .addComponent(RB_Hard)))
                                .addGap(9, 9, 9))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lines, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addComponent(cols, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cols, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(volumeMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RB_Easy)
                    .addComponent(RB_Normal)
                    .addComponent(RB_Hard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int liness = (Integer) lines.getValue();
        int colss = (Integer) cols.getValue();
        float sound = (float) volumeMusic.getValue();
        this.config.setLines(liness);
        this.config.setCols(colss);
        this.config.setSound(volumeMusic.getValue());
        this.config.WriteConfig();
        this.config.stop(SoundPlayer.clip);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void volumeMusicStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_volumeMusicStateChanged
        System.out.println("valor mudou para: " + volumeMusic.getValue());
        if (!isFirstTime) {
            this.config.changeVolume(volumeMusic.getValue());
        } else {

            this.config.play("C:\\Users\\Telmo\\Documents\\NetBeansProjects\\TetrisPoos\\src\\tetris\\resources\\Tetris.wav");

        }

        isFirstTime = false;
    }//GEN-LAST:event_volumeMusicStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        isFirstTime = false;
        this.config.setLines(20);
        this.config.setCols(20);
        lines.setValue(this.config.getLines());
        cols.setValue(this.config.getCols());
        volumeMusic.setValue(15);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (!isFirstTime) {
            this.config.stop(SoundPlayer.clip);
        }
        dispose();
        new MainApp().setVisible(true);
        this.config.play("C:\\Users\\Telmo\\Documents\\NetBeansProjects\\TetrisPoos\\src\\tetris\\resources\\Tetris.wav");
        this.config.changeVolume(this.config.getSound());
    }//GEN-LAST:event_formWindowClosed

    private void RB_HardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_HardActionPerformed
        RB_Easy.setSelected(false);
        RB_Normal.setSelected(false);
        this.config.setDifficulty(2);
    }//GEN-LAST:event_RB_HardActionPerformed

    private void RB_NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_NormalActionPerformed
        RB_Easy.setSelected(false);
        RB_Hard.setSelected(false);
        this.config.setDifficulty(1);
    }//GEN-LAST:event_RB_NormalActionPerformed

    private void RB_EasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_EasyActionPerformed
        RB_Hard.setSelected(false);
        RB_Normal.setSelected(false);
        this.config.setDifficulty(0);
    }//GEN-LAST:event_RB_EasyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            Configs dialog = new Configs(new javax.swing.JFrame(), true, new Configurations(), new SoundPlayer());
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RB_Easy;
    private javax.swing.JRadioButton RB_Hard;
    private javax.swing.JRadioButton RB_Normal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSpinner cols;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner lines;
    private javax.swing.JSlider volumeMusic;
    // End of variables declaration//GEN-END:variables
}
